name: module3_task0

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'  # todos los días a las 3:00 UTC

jobs:
  check-help:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Ejecutar make help
        run: |
          cd u3_tarea0
          make help

